on: push
name: Clippy
jobs:
    clippy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
            - run: rustup component add clippy
            - run: cd Rust && $HOME/.cargo/bin/cargo clippy --message-format=json --all-features
