on: push
name: Clippy
jobs:
    clippy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - run: rustup component add clippy
            - working-directory: Rust
            - uses: actions-rs/clippy-check@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  args: --all-features
