on: push
name: Clippy
jobs:
    clippy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
            - run: rustup component add clippy
            - run: cd Rust && $HOME/.cargo/bin/cargo clippy --message-format=json --all-features
