name: ESLint
on:
    push:
        branches-ignore:
            - main
jobs:
    ESLint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
            - name: Set Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
            - uses: pnpm/action-setup@v4
              with:
                version: 9
            - name: ci
              run: cd TypeScript && pnpm install
            - name: ESLint
              run: cd TypeScript && pnpm lint
