name: mocha
on: push
jobs:
  mocha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: ci
        run: cd TypeScript && yarn install --immutable --immutable-cache --check-cache
      - name: build & test
        run: cd TypeScript && yarn build:test
      - name: mocha
        run: cd TypeScript && yarn mocha
