name: mocha
on: push
jobs:
    mocha:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5.0.1
            - name: Set Node.js 20.x
              uses: actions/setup-node@v6
              with:
                  node-version: 24.x
            - uses: pnpm/action-setup@v4
              with:
                version: 10
            - name: ci
              run: cd TypeScript && pnpm install
            - name: build & test
              run: cd TypeScript && pnpm build:test
            - name: mocha
              run: cd TypeScript && pnpm mocha
